# Tensor Vector Arithemetics

In [2]:
import torch

In [6]:
torch_1 =  torch.tensor([2, 4, 6, 6, 34, 5])
torch_2 =  torch.tensor([23, 44, 1, 7, 323, 4])

In [ ]:
# Add the two tensors
print(torch.add(torch_1, torch_2))
print(torch_1.add(torch_2)) 
print(torch_1)
3print(torch_1.add_(torch_2))  # this update torch_1 with the result

tensor([ 25,  48,   7,  13, 357,   9])
tensor([ 25,  48,   7,  13, 357,   9])
tensor([ 2,  4,  6,  6, 34,  5])
tensor([ 25,  48,   7,  13, 357,   9])


In [12]:
# Subtraction the two tensors
print(torch.sub(torch_1, torch_2))
print(torch_1.sub(torch_2)) 
print(torch_1)

tensor([ 2,  4,  6,  6, 34,  5])
tensor([ 2,  4,  6,  6, 34,  5])
tensor([ 25,  48,   7,  13, 357,   9])


In [14]:
# Multiply the two tensors
print(torch.mul(torch_1, torch_2))
print(torch_1.mul(torch_2)) 
print(torch_1)
print(torch_1.mul_(torch_2))  # this update torch_1 with the result

tensor([   575,   2112,      7,     91, 115311,     36])
tensor([   575,   2112,      7,     91, 115311,     36])
tensor([ 25,  48,   7,  13, 357,   9])
tensor([   575,   2112,      7,     91, 115311,     36])


In [22]:
# Divide the two tensors
print(torch.div(torch_1, torch_2))
print(torch_1.div(torch_2)) 
print(torch_1)

torch_2.div(torch_1) # this update torch_1 with the result

tensor([ 25.,  48.,   7.,  13., 357.,   9.])
tensor([ 25.,  48.,   7.,  13., 357.,   9.])
tensor([   575,   2112,      7,     91, 115311,     36])


tensor([0.0400, 0.0208, 0.1429, 0.0769, 0.0028, 0.1111])

In [ ]:
# Moduls/Remainder the two tensors
print(torch.remainder(torch_1, torch_2))
print(torch_1.remainder(torch_2)) 
print(torch_1)

tensor([0, 0, 0, 0, 0, 0])
tensor([0, 0, 0, 0, 0, 0])
tensor([   13225,    92928,        7,      637, 37245453,      144])


In [25]:
# Power the two tensors
print(torch.pow(torch_1, torch_2))
print(torch_1.pow(torch_2)) 
print(torch_1)

tensor([ 7547538632788678489,                    0,                    7,
         5664003869038611701, -5766625050163001451,            429981696])
tensor([ 7547538632788678489,                    0,                    7,
         5664003869038611701, -5766625050163001451,            429981696])
tensor([   13225,    92928,        7,      637, 37245453,      144])


In [27]:
# Simply way to do

print(torch_2 + torch_1) # add
print(torch_2 - torch_1) # sub
print(torch_2 / torch_1) # div
print(torch_2 * torch_1) # mul
print(torch_2 ** torch_1) # pow
print(torch_2 % torch_1) #remainder


tensor([   13248,    92972,        8,      644, 37245776,      148])
tensor([   -13202,    -92884,        -6,      -630, -37245130,      -140])
tensor([1.7391e-03, 4.7348e-04, 1.4286e-01, 1.0989e-02, 8.6722e-06, 2.7778e-02])
tensor([     304175,     4088832,           7,        4459, 12030281319,
                576])
tensor([-3660118301321106729,                    0,                    1,
          941166106811645543,  3379465781078161427,                    0])
tensor([ 23,  44,   1,   7, 323,   4])
