# Tensor Operations

In [2]:
import torch

## Add, Subtract, Multiply, and Divide torch

In [3]:
def seperator(number: int):
    print("="*number)

torch_1 = torch.arange(3, 45)

divide_tensor = torch_1 / 255
mul_tensor = torch_1 * 255
add_tensor = torch_1 + 255
sub_tensor = torch_1 - 255

print('Divided tensors: ', divide_tensor)
seperator(100)
print('Multiply tensors: ', mul_tensor)

seperator(100)
print('Sum tensors: ', add_tensor)

seperator(100)
print('Subtract tensors: ', sub_tensor)

Divided tensors:  tensor([0.0118, 0.0157, 0.0196, 0.0235, 0.0275, 0.0314, 0.0353, 0.0392, 0.0431,
        0.0471, 0.0510, 0.0549, 0.0588, 0.0627, 0.0667, 0.0706, 0.0745, 0.0784,
        0.0824, 0.0863, 0.0902, 0.0941, 0.0980, 0.1020, 0.1059, 0.1098, 0.1137,
        0.1176, 0.1216, 0.1255, 0.1294, 0.1333, 0.1373, 0.1412, 0.1451, 0.1490,
        0.1529, 0.1569, 0.1608, 0.1647, 0.1686, 0.1725])
Multiply tensors:  tensor([  765,  1020,  1275,  1530,  1785,  2040,  2295,  2550,  2805,  3060,
         3315,  3570,  3825,  4080,  4335,  4590,  4845,  5100,  5355,  5610,
         5865,  6120,  6375,  6630,  6885,  7140,  7395,  7650,  7905,  8160,
         8415,  8670,  8925,  9180,  9435,  9690,  9945, 10200, 10455, 10710,
        10965, 11220])
Sum tensors:  tensor([258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271,
        272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285,
        286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299])
Su

## Reshape and View

In [4]:
torch_1d = torch.arange(10)
torch_1d

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
torch_reshape_1 = torch_1d.reshape(5, 2)
torch_reshape_1

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

## Get some part of the torch

In [14]:
torch_4 = torch.arange(50)
torch_5 = torch_4.reshape(2, 5, 5)

In [ ]:
# Grab the  all from dim 1, tensor bedore third row and tensor after 5 row(including)

torch_5[:, :2, 4:]

tensor([[[ 4],
         [ 9]],

        [[29],
         [34]]])

In [24]:
torch_6 = torch_5[:, :2, 4:]
torch_6.shape

torch.Size([2, 2, 1])

In [31]:
torch_6[0][1], torch_6[1][1]

(tensor([9]), tensor([34]))