# Tensors

In [1]:

import torch

In [ ]:
tensor_1d = torch.tensor([3, 2, 3, 4, 5, 5])
# show t1d tensor and dtype

tensor_1d, tensor_1d.dtype

(tensor([3, 2, 3, 4, 5, 5]), torch.int64)

In [10]:
# 2d tensor
tensor_2d = torch.zeros(3,5)
tensor_2d

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [13]:
# Multi dimentional tensor
tensor_4d = torch.rand(3,5,6,3)
tensor_4d

tensor([[[[0.0434, 0.2282, 0.0355],
          [0.1969, 0.6681, 0.7725],
          [0.7391, 0.4855, 0.6246],
          [0.0536, 0.0593, 0.3278],
          [0.3772, 0.2638, 0.6922],
          [0.8485, 0.6128, 0.3379]],

         [[0.6461, 0.5430, 0.8244],
          [0.9287, 0.3761, 0.4810],
          [0.6997, 0.1188, 0.5662],
          [0.6661, 0.0295, 0.9988],
          [0.2311, 0.8674, 0.0236],
          [0.5547, 0.9953, 0.6642]],

         [[0.7866, 0.8256, 0.3270],
          [0.2983, 0.1864, 0.9673],
          [0.5107, 0.6902, 0.2291],
          [0.4174, 0.5579, 0.5401],
          [0.4781, 0.7534, 0.7173],
          [0.8598, 0.8930, 0.1776]],

         [[0.1294, 0.5026, 0.0757],
          [0.5566, 0.4430, 0.1225],
          [0.7769, 0.6905, 0.6047],
          [0.1491, 0.5549, 0.9002],
          [0.4215, 0.8751, 0.9594],
          [0.6195, 0.4733, 0.8357]],

         [[0.3725, 0.9732, 0.6287],
          [0.9921, 0.4641, 0.0379],
          [0.1626, 0.7325, 0.4521],
          [0.7977, 0

In [17]:
# Create series of  tensor number here: 1 - 150
series_of_numbers = torch.arange(150)
series_of_numbers

tensor([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
         28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
         42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
         56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
         70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
         84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
         98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
        112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
        126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
        140, 141, 142, 143, 144, 145, 146, 147, 148, 149])